version: '3.7'

services:
  m1_service:
    build: ./m1
    volumes:
      - ./m1/src:/app/src
    ports:
      - 3001:8000
    depends_on:
      - m2_service
      - rabbitmq

  m2_service:
    build: ./m2
    volumes:
      - ./m2/src:/app/src
    ports:
      - 8000
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-alpine
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - 15672:15672